{
 "title": "MySystemMonitoring",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Нагрузка ЦП (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cpu_usgae_percentages",
     "legendFormat": "{{type}} || {{name}} ({{number_of_cores}} ядер; {{cpu_clock_speed}} ГГЦ)"
    }
   ]
  },
  {
   "title": "Диск (ГБ)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "disc_available_gigabytes", "legendFormat": "{{type}}" },
    { "expr": "disc_usage_gigabytes", "legendFormat": "{{type}} || Всего {{total}} ГБ" }
   ]
  },
  {
   "title": "Память (ГБ)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "memory_available_gigabytes", "legendFormat": "{{type}}" },
    { "expr": "memory_usage_gigabytes", "legendFormat": "{{type}} || Всего {{total}} ГБ" }
   ]
  },
  {
   "title": "Диспетчер задач",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "process_cpu_usage_percentages", "legendFormat": "__auto" },
    { "expr": "process_memory_usage_megabytes", "legendFormat": "__auto" }
   ]
  }
 ]
}